// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebProjectManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebProjectManagementSystem.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("WebProjectManagementSystem.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WebProjectManagementSystem.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9597),
                            Description = "First project",
                            EndDate = new DateTime(2024, 12, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9667),
                            Name = "Project Alpha",
                            StartDate = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9664),
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9662)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9673),
                            Description = "Second project",
                            EndDate = new DateTime(2025, 3, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9678),
                            Name = "Project Beta",
                            StartDate = new DateTime(2024, 10, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9676),
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9675)
                        });
                });

            modelBuilder.Entity("WebProjectManagementSystem.Models.ProjectUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProjectUsers");
                });

            modelBuilder.Entity("WebProjectManagementSystem.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = 1,
                            CreatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9872),
                            Description = "First task",
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            Status = "New",
                            Title = "InitialTask",
                            UpdatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9874)
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = 2,
                            CreatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9877),
                            Description = "Second task",
                            DueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 2,
                            Status = "In Progress",
                            Title = "InitialTask",
                            UpdatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9879)
                        });
                });

            modelBuilder.Entity("WebProjectManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9823),
                            Email = "eryordanova@panda.com",
                            FirstName = "Erika",
                            LastName = "Yordanova",
                            PasswordHash = "123456",
                            RoleType = "Admin",
                            UpdatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9827),
                            Username = "eryordanova"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9832),
                            Email = "vyordanova@panda.com",
                            FirstName = "Viktoria",
                            LastName = "Yordanova",
                            PasswordHash = "1234567",
                            RoleType = "User",
                            UpdatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9833),
                            Username = "vyordanova"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9835),
                            Email = "akehaiova@panda.com",
                            FirstName = "Adelina",
                            LastName = "Kehaiova",
                            PasswordHash = "Adi123",
                            RoleType = "User",
                            UpdatedAt = new DateTime(2024, 9, 8, 11, 27, 0, 626, DateTimeKind.Local).AddTicks(9836),
                            Username = "akehaiova"
                        });
                });

            modelBuilder.Entity("WebProjectManagementSystem.Models.Task", b =>
                {
                    b.HasOne("WebProjectManagementSystem.Models.Project", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebProjectManagementSystem.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
